language: python

python:
- 3.6

addons:
  apt_packages:
     - libcups2-dev

services:
- mysql

branches:
  only:
  - develop

install:
- pip install --upgrade pip
- pip install -e .
- pip install -r requirements.txt
- pip install flake8
- pip install coveralls

before_script:
- flake8 ambition_reference
- mysql -e 'create database edc character set utf8;'

script:
- coverage run --source=ambition_reference manage.py test

after_success:
- coveralls